# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:
.PHONY : .NOTPARALLEL

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /filestorage/git/ts17-ai

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /filestorage/git/ts17-ai

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /filestorage/git/ts17-ai/CMakeFiles /filestorage/git/ts17-ai/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /filestorage/git/ts17-ai/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ai

# Build rule for target.
ai: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ai
.PHONY : ai

# fast build rule for target.
ai/fast:
	$(MAKE) -f CMakeFiles/ai.dir/build.make CMakeFiles/ai.dir/build
.PHONY : ai/fast

ai/ai.o: ai/ai.cpp.o
.PHONY : ai/ai.o

# target to build an object file
ai/ai.cpp.o:
	$(MAKE) -f CMakeFiles/ai.dir/build.make CMakeFiles/ai.dir/ai/ai.cpp.o
.PHONY : ai/ai.cpp.o

ai/ai.i: ai/ai.cpp.i
.PHONY : ai/ai.i

# target to preprocess a source file
ai/ai.cpp.i:
	$(MAKE) -f CMakeFiles/ai.dir/build.make CMakeFiles/ai.dir/ai/ai.cpp.i
.PHONY : ai/ai.cpp.i

ai/ai.s: ai/ai.cpp.s
.PHONY : ai/ai.s

# target to generate assembly for a file
ai/ai.cpp.s:
	$(MAKE) -f CMakeFiles/ai.dir/build.make CMakeFiles/ai.dir/ai/ai.cpp.s
.PHONY : ai/ai.cpp.s

ai/teamstyle17.o: ai/teamstyle17.cpp.o
.PHONY : ai/teamstyle17.o

# target to build an object file
ai/teamstyle17.cpp.o:
	$(MAKE) -f CMakeFiles/ai.dir/build.make CMakeFiles/ai.dir/ai/teamstyle17.cpp.o
.PHONY : ai/teamstyle17.cpp.o

ai/teamstyle17.i: ai/teamstyle17.cpp.i
.PHONY : ai/teamstyle17.i

# target to preprocess a source file
ai/teamstyle17.cpp.i:
	$(MAKE) -f CMakeFiles/ai.dir/build.make CMakeFiles/ai.dir/ai/teamstyle17.cpp.i
.PHONY : ai/teamstyle17.cpp.i

ai/teamstyle17.s: ai/teamstyle17.cpp.s
.PHONY : ai/teamstyle17.s

# target to generate assembly for a file
ai/teamstyle17.cpp.s:
	$(MAKE) -f CMakeFiles/ai.dir/build.make CMakeFiles/ai.dir/ai/teamstyle17.cpp.s
.PHONY : ai/teamstyle17.cpp.s

communicate/communicate.o: communicate/communicate.cpp.o
.PHONY : communicate/communicate.o

# target to build an object file
communicate/communicate.cpp.o:
	$(MAKE) -f CMakeFiles/ai.dir/build.make CMakeFiles/ai.dir/communicate/communicate.cpp.o
.PHONY : communicate/communicate.cpp.o

communicate/communicate.i: communicate/communicate.cpp.i
.PHONY : communicate/communicate.i

# target to preprocess a source file
communicate/communicate.cpp.i:
	$(MAKE) -f CMakeFiles/ai.dir/build.make CMakeFiles/ai.dir/communicate/communicate.cpp.i
.PHONY : communicate/communicate.cpp.i

communicate/communicate.s: communicate/communicate.cpp.s
.PHONY : communicate/communicate.s

# target to generate assembly for a file
communicate/communicate.cpp.s:
	$(MAKE) -f CMakeFiles/ai.dir/build.make CMakeFiles/ai.dir/communicate/communicate.cpp.s
.PHONY : communicate/communicate.cpp.s

communicate/dll_main.o: communicate/dll_main.cpp.o
.PHONY : communicate/dll_main.o

# target to build an object file
communicate/dll_main.cpp.o:
	$(MAKE) -f CMakeFiles/ai.dir/build.make CMakeFiles/ai.dir/communicate/dll_main.cpp.o
.PHONY : communicate/dll_main.cpp.o

communicate/dll_main.i: communicate/dll_main.cpp.i
.PHONY : communicate/dll_main.i

# target to preprocess a source file
communicate/dll_main.cpp.i:
	$(MAKE) -f CMakeFiles/ai.dir/build.make CMakeFiles/ai.dir/communicate/dll_main.cpp.i
.PHONY : communicate/dll_main.cpp.i

communicate/dll_main.s: communicate/dll_main.cpp.s
.PHONY : communicate/dll_main.s

# target to generate assembly for a file
communicate/dll_main.cpp.s:
	$(MAKE) -f CMakeFiles/ai.dir/build.make CMakeFiles/ai.dir/communicate/dll_main.cpp.s
.PHONY : communicate/dll_main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... ai"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... ai/ai.o"
	@echo "... ai/ai.i"
	@echo "... ai/ai.s"
	@echo "... ai/teamstyle17.o"
	@echo "... ai/teamstyle17.i"
	@echo "... ai/teamstyle17.s"
	@echo "... communicate/communicate.o"
	@echo "... communicate/communicate.i"
	@echo "... communicate/communicate.s"
	@echo "... communicate/dll_main.o"
	@echo "... communicate/dll_main.i"
	@echo "... communicate/dll_main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

